# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zNwcREgJMFFoJLJkDKMXpAbsv-27tjMV
"""

import numpy as np
import matplotlib.pyplot as plt

# 定数（単位系は自然単位系: ℏ = 1, 2m = 1）
hbar = 1
m = 0.5  # 2m=1より
a = 1.0  # 格子定数
P = 10.0  # ポテンシャル強度（無次元）

# エネルギー範囲の設定
E_vals = np.linspace(0.01, 100, 1000)  # エネルギーのスキャン範囲
k_vals = []  # 許されるkの値を格納

for E in E_vals:
    q = np.sqrt(2 * m * E) / hbar
    lhs = np.cos(q * a) + P / (q * a) * np.sin(q * a)
    if np.abs(lhs) <= 1:
        k = np.arccos(lhs) / a
        k_vals.append([E, k])
        # 負のkも加える（対称性）
        k_vals.append([E, -k])

# 配列に変換してプロット
k_vals = np.array(k_vals)
plt.figure(figsize=(8, 6))
plt.scatter(k_vals[:, 1], k_vals[:, 0], s=1, color='blue')
plt.xlabel("Wavevector k")
plt.ylabel("Energy E")
plt.title("Kronig-Penney Model: E-k Dispersion")
plt.grid(True)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import interact, FloatSlider

# 定数
k_B = 8.617e-5
Eg = 1.1
Ef = 0.0
Ec = Eg / 2
Ev = -Eg / 2

Nc = 2.8e19
Nv = 1.04e19

def intrinsic_density(T):
    return np.sqrt(Nc * Nv) * np.exp(-Eg / (2 * k_B * T))

def density_to_points(n):
    log_n = np.log10(n)
    return int(np.clip((log_n - 8) * 20, 0, 300))

def sample_conduction(T, n_points):
    # Ecからの距離を指数分布で生成
    scale = k_B * T  # 温度で広がる
    dE = np.random.exponential(scale=scale, size=n_points)
    return Ec + dE

def sample_valence(T, n_points):
    scale = k_B * T
    dE = np.random.exponential(scale=scale, size=n_points)
    return Ev - dE

def plot_band(T):
    ni = intrinsic_density(T)
    n_points = density_to_points(ni)

    plt.figure(figsize=(5, 8))

    # バンド
    plt.plot([0, 1], [Ec, Ec], 'k', linewidth=2)
    plt.plot([0, 1], [Ev, Ev], 'k', linewidth=2)
    plt.plot([0, 1], [Ef, Ef], 'r--')

    # 電子（Ec付近に集中）
    if n_points > 0:
        y_e = sample_conduction(T, n_points)
        x_e = np.random.uniform(0.2, 0.8, size=n_points)
        plt.scatter(x_e, y_e, s=10, label="Electrons")

    # 正孔（Ev付近に集中）
    if n_points > 0:
        y_h = sample_valence(T, n_points)
        x_h = np.random.uniform(0.2, 0.8, size=n_points)
        plt.scatter(x_h, y_h, s=10, label="Holes")

    plt.xlim(0, 1)
    plt.ylim(-1.5, 1.5)
    plt.xticks([])
    plt.ylabel("Energy (eV)")
    plt.title(f"T = {T:.0f} K, ni ≈ {ni:.2e} cm^-3")
    plt.legend()

    plt.show()

interact(plot_band,
         T=FloatSlider(value=300, min=50, max=1000, step=50));

import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import interact

# 定数
k_B = 8.617e-5  # eV/K
Eg = 1.12       # Si bandgap [eV]

def calc_ni(T):
    A = 5.2e15
    return A * (T**1.5) * np.exp(-Eg / (2 * k_B * T))

def plot_ni(T):
    T_range = np.linspace(200, 600, 300)
    ni = calc_ni(T_range)

    invT = 1 / T_range
    invT_point = 1 / T

    plt.figure()
    plt.semilogy(invT, ni)
    plt.scatter(invT_point, calc_ni(T), s=80)

    plt.xlabel("1 / Temperature (1/K)")
    plt.ylabel("Intrinsic carrier density (cm^-3)")
    plt.title("Arrhenius Plot of Si intrinsic carrier density")

    plt.gca().invert_xaxis()  # ←重要（低温が右になる）
    plt.show()

# スライダー（シンプル版の方が安定）
interact(plot_ni, T=(200, 600, 10));

"""import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import interact

# 定数
k_B = 8.617e-5  # eV/K
Eg = 1.12       # Si bandgap [eV]

def calc_ni(T):
    A = 5.2e15
    return A * (T**1.5) * np.exp(-Eg / (2 * k_B * T))

def plot_ni(T):
    T_range = np.linspace(200, 600, 300)
    ni = calc_ni(T_range)

    plt.figure()
    plt.semilogy(T_range, ni)
    plt.scatter(T, calc_ni(T), s=80)

    plt.xlabel("Temperature (K)")
    plt.ylabel("Intrinsic carrier density (cm^-3)")
    plt.title("Si intrinsic carrier density vs Temperature")

    plt.show()

# スライダー（安定版）
interact(plot_ni, T=(200, 600, 10));
"""

import numpy as np
import matplotlib.pyplot as plt

theta = np.linspace(0, 2*np.pi, 2000)
r = theta * np.sin(5*theta)

x = r * np.cos(theta)
y = r * np.sin(theta)

plt.figure(figsize=(4,6))
plt.plot(x, y, linewidth=2)
plt.axis('equal')
plt.axis('off')
plt.title("Christmas Tree (Polar Equation)")
plt.show()

"""import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import interact

# 定数
k_B = 8.617e-5  # eV/K
Eg = 1.12       # Si bandgap [eV]

def calc_ni(T):
    A = 5.2e15
    return A * (T**1.5) * np.exp(-Eg / (2 * k_B * T))

def plot_ni(T):
    T_range = np.linspace(200, 600, 300)
    ni = calc_ni(T_range)

    plt.figure()
    plt.semilogy(T_range, ni)
    plt.scatter(T, calc_ni(T), s=80)

    plt.xlabel("Temperature (K)")
    plt.ylabel("Intrinsic carrier density (cm^-3)")
    plt.title("Si intrinsic carrier density vs Temperature")

    plt.show()

# スライダー（安定版）
interact(plot_ni, T=(200, 600, 10));
"""

import numpy as np
import matplotlib.pyplot as plt

# 定数
q = 1.602e-19      # 電子の電荷 [C]
k = 1.381e-23      # ボルツマン定数 [J/K]
T = 300            # 絶対温度 [K]
n = 1              # 理想ity factor（仮定）

# バンドギャップ [eV]
materials = {
    'Si (1.1 eV)': 1.1,
    'GaN (3.4 eV)': 3.4,
    'Ga₂O₃ (4.8 eV)': 4.8
}

# 電圧範囲（順方向のみに限定）
V = np.linspace(0, 1, 500)

# グラフ描画
plt.figure(figsize=(8,6))

for label, Eg in materials.items():
    Eg_J = Eg * q
    Is = np.exp(-Eg_J / (k * T))  # 飽和電流の近似（単位省略）
    I = Is * (np.exp(q * V / (n * k * T)) - 1)
    I[I <= 0] = 1e-30  # logプロットのためゼロ以下を処理
    plt.semilogy(V, I, label=label)

# グラフ装飾
plt.xlabel("Voltage (V)", fontsize=14)
plt.ylabel("Forward Current (arb. unit, log scale)", fontsize=14)
plt.title("Comparison of Turn-on Behavior by Bandgap", fontsize=16)
plt.grid(True, which='both', linestyle='--', linewidth=0.5)
plt.legend(fontsize=12)
plt.xlim(0, 1)
plt.ylim(1e-30, 1e0)  # リークから立ち上がりまで広くカバー
plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import interact

# 定数
k_B = 8.617e-5  # eV/K
Eg = 1.12       # Si bandgap [eV]

def calc_ni(T):
    A = 5.2e15
    return A * (T**1.5) * np.exp(-Eg / (2 * k_B * T))

def plot_ni(T):
    T_range = np.linspace(200, 600, 300)
    ni = calc_ni(T_range)

    plt.figure()
    plt.semilogy(T_range, ni)
    plt.scatter(T, calc_ni(T), s=80)

    plt.xlabel("Temperature (K)")
    plt.ylabel("Intrinsic carrier density (cm^-3)")
    plt.title("Si intrinsic carrier density vs Temperature")

    plt.show()

# スライダー（安定版）
interact(plot_ni, T=(200, 600, 10));

import numpy as np
import matplotlib.pyplot as plt

def draw_branch(x, y, length, angle, depth, s=0.72, alpha=np.deg2rad(28)):
    if depth == 0:
        return
    x2 = x + length * np.cos(angle)
    y2 = y + length * np.sin(angle)
    plt.plot([x, x2], [y, y2], linewidth=1)

    # 左右に分岐
    draw_branch(x2, y2, length*s, angle + alpha, depth-1, s, alpha)
    draw_branch(x2, y2, length*s, angle - alpha, depth-1, s, alpha)

plt.figure(figsize=(5,7))
draw_branch(0.0, 0.0, length=1.0, angle=np.pi/2, depth=11)
plt.axis('equal')
plt.axis('off')
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# 定数
q = 1.602e-19      # 電子の電荷 [C]
k = 1.381e-23      # ボルツマン定数 [J/K]
T = 300            # 絶対温度 [K]
n = 1              # 理想ity factor（仮定）

# バンドギャップ [eV]
materials = {
    'Si (1.1 eV)': 1.1,
    'GaN (3.4 eV)': 3.4,
    'Ga₂O₃ (4.8 eV)': 4.8
}

# 電圧範囲（逆バイアスから順バイアスまで）
V = np.linspace(-2, 1, 500)

# グラフ描画
plt.figure(figsize=(8,6))
for label, Eg in materials.items():
    # Eg[eV] → J へ変換
    Eg_J = Eg * q
    # 飽和電流密度（指数近似式、正規化のため定数省略）
    Is = np.exp(-Eg_J / (k * T))
    # ダイオード式（逆方向～順方向）
    I = Is * (np.exp(q * V / (n * k * T)) - 1)
    plt.semilogy(V, np.abs(I), label=label)  # 絶対値でlog表示

# グラフ装飾
plt.xlabel("Voltage (V)", fontsize=14)
plt.ylabel("Current (arb. unit)", fontsize=14)
plt.title("Simulated I-V Characteristics for Different Bandgaps", fontsize=16)
plt.grid(True, which='both', linestyle='--', linewidth=0.5)
plt.legend(fontsize=12)
plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# グリッド作成
x = np.linspace(-3, 3, 800)
y = np.linspace(-3, 3, 800)
X, Y = np.meshgrid(x, y)

# 極座標変換
R = np.sqrt(X**2 + Y**2)
Theta = np.arctan2(Y, X)

# 雪結晶関数
sigma = 1.2
Z = np.exp(-(R**2)/(sigma**2)) * np.cos(6 * Theta + 0.05*np.random.randn(*Theta.shape))



# 描画
plt.figure(figsize=(6, 6))
plt.contour(X, Y, Z, levels=15, linewidths=1.5)
plt.axis('equal')
plt.axis('off')
plt.show()

Z = np.exp(-(R**2)/(sigma**2)) * np.cos(6 * Theta) * (1 + 0.15*np.cos(12*Theta))

import numpy as np
import matplotlib.pyplot as plt

# 飽和ドリフト速度 [m/s]
v_sat = 2e5  # GaNの例（2×10^7 cm/s）

# ゲート長 [nm]：10 ～ 10,000 nm
Lg_nm = np.logspace(1, 4, 300)
Lg_m = Lg_nm * 1e-9

# カットオフ周波数 [Hz] → [GHz]
f_T = v_sat / (2 * np.pi * Lg_m)
f_T_GHz = f_T * 1e-9

# プロット
fig, ax = plt.subplots(figsize=(8,6))
ax.loglog(Lg_nm, f_T_GHz, color='black')

# 軸ラベル・タイトル
ax.set_xlabel("Gate Length $L_g$ [nm]", fontsize=14)
ax.set_ylabel("Cut-off Frequency $f_T$ [GHz]", fontsize=14)
ax.set_title("Effect of Gate Length on Cut-off Frequency", fontsize=16)

# 軸範囲
ax.set_xlim(10, 1e4)
ax.set_ylim(1, 1e4)

# グリッド
ax.grid(True, which='both', linestyle='--', linewidth=0.5)

# メモリ（ticks）を内側に設定
ax.tick_params(axis='both', which='both', direction='in')

# レイアウト調整と表示
plt.tight_layout()
plt.show()

import numpy as np

# === パラメータ設定 ===
Pt_dBm = 30               # HEMTの出力電力 [dBm] → 1W
Gt_dBi = 15               # 送信アンテナ利得 [dBi]
Gr_dBi = 0                # 受信アンテナ利得 [dBi]
freq_GHz = 28             # 周波数 [GHz]（例：5Gミリ波）
Pr_min_dBm = -90          # 受信最小電力 [dBm]（感度）

# === 単位変換 ===
Pt = 10**((Pt_dBm - 30)/10)      # [W]
Gt = 10**(Gt_dBi / 10)           # 無次元
Gr = 10**(Gr_dBi / 10)
c = 3e8                          # 光速 [m/s]
f = freq_GHz * 1e9              # 周波数 [Hz]
lam = c / f                     # 波長 [m]
Pr_min = 10**((Pr_min_dBm - 30)/10)  # 最小受信電力 [W]

# === Friis式から搬送距離 d を解く ===
d = (lam / (4 * np.pi)) * np.sqrt(Pt * Gt * Gr / Pr_min)

# 結果表示
print(f"最大搬送距離：{d:.2f} m（HEMT出力 {Pt_dBm} dBm, 周波数 {freq_GHz} GHz）")

import numpy as np
import matplotlib.pyplot as plt

# 材料ごとの飽和速度 [m/s]
materials = {
    'Ga₂O₃': 2e5,
    'Si':    1.0e5,
    'SiC':   1.5e5,
    'GaN':   2.5e5
}

# ゲート長 [nm]：10 ～ 10,000 nm
Lg_nm = np.logspace(1, 4, 300)
Lg_m = Lg_nm * 1e-9

# グラフ初期化
fig, ax = plt.subplots(figsize=(8,6))

# 各材料ごとにカットオフ周波数計算・プロット
for label, vsat in materials.items():
    f_T = vsat / (2 * np.pi * Lg_m)  # [Hz]
    ax.loglog(Lg_nm, f_T * 1e-9, label=label)  # GHzに変換

# 軸ラベル・タイトル
ax.set_xlabel("Gate Length $L_g$ [nm]", fontsize=14)
ax.set_ylabel("Cut-off Frequency $f_T$ [GHz]", fontsize=14)
ax.set_title("Cut-off Frequency vs. Gate Length for Different Materials", fontsize=16)

# 軸範囲・目盛方向
ax.set_xlim(10, 1e4)
ax.set_ylim(1, 1e4)
ax.tick_params(axis='both', which='both', direction='in')

# グリッド・凡例
ax.grid(True, which='both', linestyle='--', linewidth=0.5)
ax.legend(fontsize=12)
plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from scipy.constants import e, epsilon_0, hbar, m_e
from scipy.linalg import eigh_tridiagonal

# 定数
x_Al = 0.3
t_AlGaN = 20e-9  # 20 nm
L_total = 40e-9  # 全体厚さ
N = 1000
z = np.linspace(0, L_total, N)
dz = z[1] - z[0]

# 材料定数
Eg_GaN = 3.4  # eV
Eg_AlN = 6.2  # eV
epsilon_r = 9.5  # 相対誘電率（GaN近似）
m_eff = 0.2 * m_e  # 有効質量（GaN近似）
Ec_offset = 0.7 * (x_Al * (Eg_AlN - Eg_GaN))  # 伝導帯オフセット

# 分極電荷密度（C/m^2）：近似式（AlGaN-GaN界面）
P_sp_GaN = -0.029  # C/m^2
P_sp_AlGaN = -0.081 + 0.052 * (1 - x_Al)  # C/m^2（近似）
P_pe = -0.034 * x_Al  # 圧電分極（近似）
delta_P = P_sp_AlGaN + P_pe - P_sp_GaN
sigma = delta_P  # 面分極電荷（C/m^2）

# 内部電場（AlGaN層内）
E_field = -sigma / (epsilon_0 * epsilon_r)  # V/m

# 伝導帯ポテンシャルプロファイル（AlGaN内は傾斜井戸）
V = np.zeros(N)
for i in range(N):
    if z[i] < t_AlGaN:
        V[i] = Ec_offset - e * E_field * (t_AlGaN - z[i]) / e  # eで割って[eV]に
    else:
        V[i] = 0  # GaNバルク

# シュレーディンガー方程式：3点差分で固有値・固有状態を求める
main_diag = V + hbar**2 / (m_eff * dz**2) * 1
off_diag = -0.5 * hbar**2 / (m_eff * dz**2) * np.ones(N-1)
eigvals, eigvecs = eigh_tridiagonal(main_diag, off_diag)

# 基底状態のみ表示
E0 = eigvals[0] / e  # J → eV
psi0 = eigvecs[:, 0]
psi0 = psi0 / np.sqrt(np.sum(np.abs(psi0)**2) * dz)  # 正規化

# 電子密度（基底状態のみ）
n2D = 1e13 * 1e4  # 2DEG密度: 1e13 cm^-2 → m^-2
rho = -e * n2D * np.abs(psi0)**2  # 空間電荷密度 [C/m^3]

# ポアソン方程式（1次元）
phi = np.zeros(N)
for i in range(1, N-1):
    phi[i] = phi[i-1] + dz**2 * rho[i] / (epsilon_0 * epsilon_r)

# ポテンシャル補正を加味したバンド構造
V_eff = V + phi / e  # [eV]

# 描画
plt.figure(figsize=(10, 5))
plt.plot(z * 1e9, V, label='Band Edge w/o charge')
plt.plot(z * 1e9, V_ef_*

import numpy as np
import matplotlib.pyplot as plt
from scipy.constants import e, epsilon_0, hbar, m_e

# -------------------------
# 材料パラメータ（概算）
# -------------------------
x_Al = 0.2  # Al組成（例: Al₀.₂Ga₀.₈O₃）
Eg_Ga2O3 = 4.9       # [eV]
Eg_Al2O3 = 8.8       # [eV]（仮定）

# 組成依存バンドギャップ（直線補間）
Eg_AlGaO3 = Eg_Ga2O3 * (1 - x_Al) + Eg_Al2O3 * x_Al

# バンドオフセットの仮定（比率）
ΔEc_ratio = 0.7  # 伝導帯オフセット比（70%が伝導帯側と仮定）
ΔEc = ΔEc_ratio * (Eg_AlGaO3 - Eg_Ga2O3)  # [eV]

# 物理定数とパラメータ
eps_r = 10  # Ga2O3の比誘電率（概算）
eps = epsilon_0 * eps_r
d_AlGaO3 = 10e-9  # バリア層厚さ [m]
m_eff = 0.28 * m_e  # 有効質量（参考値）

# シンプルな分極電荷（今回は誘電バリアのみ仮定）
σ_pol = eps * ΔEc / (e * d_AlGaO3)  # [C/m^2]

# 2DEG密度 [cm^-2]
n_2DEG = σ_pol / e / 1e4  # [cm^-2]

print(f"Al組成: {x_Al}, バンドギャップ: {Eg_AlGaO3:.2f} eV")
print(f"伝導帯オフセット ΔEc: {ΔEc:.2f} eV")
print(f"2DEG密度: {n_2DEG:.2e} cm⁻²")

import numpy as np
import matplotlib.pyplot as plt

# パラメータ設定
Pt_dBm_list = [20, 30, 40]  # HEMT出力 [dBm] → 100mW, 1W, 10W
Gt_dBi = 15                 # 送信アンテナ利得 [dBi]
Gr_dBi = 0                  # 受信アンテナ利得 [dBi]
Pr_min_dBm = -90            # 最小受信電力 [dBm]
Gt = 10**(Gt_dBi / 10)      # 無次元
Gr = 10**(Gr_dBi / 10)
c = 3e8                     # 光速 [m/s]
Pr_min = 10**((Pr_min_dBm - 30)/10)  # [W]

# 周波数範囲（0.5GHz〜100GHz）
freq_GHz = np.logspace(np.log10(0.5), np.log10(100), 500)
f = freq_GHz * 1e9  # [Hz]
lam = c / f         # 波長 [m]

# グラフ作成
plt.figure(figsize=(12, 8))

for Pt_dBm in Pt_dBm_list:
    Pt = 10**((Pt_dBm - 30)/10)  # [W]
    d = (lam / (4 * np.pi)) * np.sqrt(Pt * Gt * Gr / Pr_min)  # [m]
    label = f"{Pt_dBm} dBm ({int(Pt*1000)} mW)"
    plt.plot(freq_GHz, d, label=label, linewidth=2)

# 軸設定
plt.xscale("log")
plt.yscale("log")
plt.xlim(0.5, 100)  # 横軸のレンジを0.5〜100 GHzに設定
plt.xlabel("Frequency [GHz]", fontsize=20)
plt.ylabel("Maximum Carrier Distance [m]", fontsize=20)
#plt.title("Carrier Distance vs Frequency\nfor Different HEMT Output Powers", fontsize=20)
plt.grid(True, which="both", linestyle="--", alpha=0.5)
plt.legend(fontsize=20)
plt.xticks(fontsize=20)
plt.yticks(fontsize=20)
plt.tight_layout()
plt.show()



z = np.linspace(0, 20e-9, 1000)  # [m]
V = np.zeros_like(z)
V[z < d_AlGaO3] = ΔEc  # バリア層にΔEcを与える

plt.plot(z * 1e9, V)
plt.xlabel("Depth (nm)", fontsize=14)
plt.ylabel("Conduction Band Edge (eV)", fontsize=14)
plt.title("AlGaO₃/Ga₂O₃ Band Profile", fontsize=15)
plt.grid(True)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import fsolve

# 定数
k_B = 8.617333262145e-5  # [eV/K]
Eg = 1.12  # バンドギャップ [eV]
Ed = 0.045  # アクセプタ準位 [eV]

# 有効状態密度（温度依存）
def Nc(T): return 2.8e19 * (T / 300)**1.5
def Nv(T): return 1.04e19 * (T / 300)**1.5
def ni(T): return np.sqrt(Nc(T) * Nv(T)) * np.exp(-Eg / (2 * k_B * T))

# 電気的中性式
def neutrality(Ef, T, Na):
    n = Nc(T) * np.exp(-(Eg - Ef) / (k_B * T))
    p = Nv(T) * np.exp(-Ef / (k_B * T))
    Na_minus = Na / (1 + 0.5 * np.exp((Ef - Ed) / (k_B * T)))
    return p + Na_minus - n

# 精密な正孔密度計算
def calc_precise_p(Na, T_array):
    p_list = []
    for T in T_array:
        Ef_guess = Eg / 2
        Ef = fsolve(neutrality, Ef_guess, args=(T, Na))[0]
        p = Nv(T) * np.exp(-Ef / (k_B * T))
        p_list.append(p)
    return np.array(p_list)

# 計算
T_range = np.linspace(100, 1200, 300)
Na_list = {
    r"$N_a=10^{15}$ cm$^{-3}$": 1e15,
    r"$N_a=10^{17}$ cm$^{-3}$": 1e17,
    r"$N_a=10^{19}$ cm$^{-3}$": 1e19,
}

plt.figure(figsize=(9, 6))
for label, Na in Na_list.items():
    p = calc_precise_p(Na, T_range)
    plt.plot(T_range, p, label=label)

plt.plot(T_range, [ni(T) for T in T_range], '--k', label="真性キャリア密度 $n_i$")
plt.yscale("log")
plt.xlabel("温度 T [K]")
plt.ylabel("正孔密度 p [cm$^{-3}$]")
plt.title("自己無撞着計算によるp型半導体のキャリア密度")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from scipy.constants import e, epsilon_0, hbar, m_e
from scipy.linalg import eigh_tridiagonal

# 定数
x_Al = 0.3
t_AlGaN = 20e-9  # 20 nm
L_total = 40e-9  # 全体厚さ
N = 1000
z = np.linspace(0, L_total, N)
dz = z[1] - z[0]

# 材料定数
Eg_GaN = 3.4  # eV
Eg_AlN = 6.2  # eV
epsilon_r = 9.5  # 相対誘電率（GaN近似）
m_eff = 0.2 * m_e  # 有効質量（GaN近似）
Ec_offset = 0.7 * (x_Al * (Eg_AlN - Eg_GaN))  # 伝導帯オフセット

# 分極電荷密度（C/m^2）：近似式（AlGaN-GaN界面）
P_sp_GaN = -0.029  # C/m^2
P_sp_AlGaN = -0.081 + 0.052 * (1 - x_Al)  # C/m^2（近似）
P_pe = -0.034 * x_Al  # 圧電分極（近似）
delta_P = P_sp_AlGaN + P_pe - P_sp_GaN
sigma = delta_P  # 面分極電荷（C/m^2）

# 内部電場（AlGaN層内）
E_field = -sigma / (epsilon_0 * epsilon_r)  # V/m

# 伝導帯ポテンシャルプロファイル（AlGaN内は傾斜井戸）
V = np.zeros(N)
for i in range(N):
    if z[i] < t_AlGaN:
        V[i] = Ec_offset - e * E_field * (t_AlGaN - z[i]) / e  # eで割って[eV]に
    else:
        V[i] = 0  # GaNバルク

# シュレーディンガー方程式：3点差分で固有値・固有状態を求める
main_diag = V + hbar**2 / (m_eff * dz**2) * 1
off_diag = -0.5 * hbar**2 / (m_eff * dz**2) * np.ones(N-1)
eigvals, eigvecs = eigh_tridiagonal(main_diag, off_diag)

# 基底状態のみ表示
E0 = eigvals[0] / e  # J → eV
psi0 = eigvecs[:, 0]
psi0 = psi0 / np.sqrt(np.sum(np.abs(psi0)**2) * dz)  # 正規化

# 電子密度（基底状態のみ）
n2D = 1e13 * 1e4  # 2DEG密度: 1e13 cm^-2 → m^-2
rho = -e * n2D * np.abs(psi0)**2  # 空間電荷密度 [C/m^3]

# ポアソン方程式（1次元）
phi = np.zeros(N)
for i in range(1, N-1):
    phi[i] = phi[i-1] + dz**2 * rho[i] / (epsilon_0 * epsilon_r)

# ポテンシャル補正を加味したバンド構造
V_eff = V + phi / e  # [eV]

# 描画
plt.figure(figsize=(10, 5))
plt.plot(z * 1e9, V, label='Band Edge w/o charge')
plt.plot(z * 1e9, V_ef_*

import numpy as np
import matplotlib.pyplot as plt
from scipy.constants import e, epsilon_0, hbar, m_e
from scipy.linalg import eigh_tridiagonal

# --- パラメータ設定 ---
x_Al = 0.3
t_AlGaN = 20e-9  # 20 nm
L_total = 40e-9  # 全体厚さ [m]
N = 1000
z = np.linspace(0, L_total, N)
dz = z[1] - z[0]

# --- 材料定数 ---
Eg_GaN = 3.4  # eV
Eg_AlN = 6.2  # eV
epsilon_r = 9.5  # 相対誘電率（GaN近似）
m_eff = 0.2 * m_e  # 有効質量
Ec_offset = 0.7 * (x_Al * (Eg_AlN - Eg_GaN))  # [eV]

# --- 分極電荷と電場 ---
P_sp_GaN = -0.029  # C/m^2
P_sp_AlGaN = -0.081 + 0.052 * (1 - x_Al)  # C/m^2（簡易近似）
P_pe = -0.034 * x_Al  # 圧電分極
delta_P = P_sp_AlGaN + P_pe - P_sp_GaN
sigma = delta_P  # 面電荷密度 [C/m^2]
E_field = -sigma / (epsilon_0 * epsilon_r)  # V/m

# --- バンドエッジプロファイル（分極電場あり） ---
V = np.zeros(N)
for i in range(N):
    if z[i] < t_AlGaN:
        V[i] = Ec_offset - E_field * (t_AlGaN - z[i])  # [eV]
    else:
        V[i] = 0  # GaNバルク

# --- シュレーディンガー方程式（1D 3点差分） eV単位に修正 ---
factor = hbar**2 / (m_eff * dz**2) / e  # eV単位に変換
main_diag = V + factor * np.ones(N)
off_diag = -0.5 * factor * np.ones(N - 1)
eigvals, eigvecs = eigh_tridiagonal(main_diag, off_diag)


# --- 基底状態のみ抽出 ---
E0 = eigvals[0] / e  # J → eV
psi0 = eigvecs[:, 0]
psi0 = psi0 / np.sqrt(np.sum(np.abs(psi0)**2) * dz)  # 正規化

# --- 電子密度とポアソン方程式解 ---
n2D = 1e13 * 1e4  # 2DEG密度 [cm^-2] → [m^-2]
rho = -e * n2D * np.abs(psi0)**2  # C/m^3

phi = np.zeros(N)
for i in range(1, N-1):
    phi[i] = phi[i-1] + dz**2 * rho[i] / (epsilon_0 * epsilon_r)

V_eff = V + phi / e  # [eV]

# --- 描画 ---
plt.figure(figsize=(10, 5))
plt.plot(z * 1e9, V, label='Band Edge (without space charge)')
plt.plot(z * 1e9, V_eff, label='Band Edge (with self-consistent correction)')
plt.plot(z * 1e9, E0 * np.ones_like(z), 'r--', label='Bound State E₀')
plt.plot(z * 1e9, psi0 * 0.05 + E0, 'm-', label='ψ₀ (scaled)')

plt.axvline(x=t_AlGaN * 1e9, color='gray', linestyle='--', label='AlGaN/GaN Interface')
plt.xlabel('Depth [nm]')
plt.ylabel('Energy [eV]')
plt.title('Al₀.₃Ga₀.₇N/GaN Band Structure with Polarization and 2DEG')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

import numpy as np
from scipy.constants import epsilon_0, e, hbar, m_e

# -------------------------
# パラメータ設定
# -------------------------
# 材料パラメータ（例：Al₀.₃Ga₀.₇N/GaN構造）
x_Al = 0.3  # Al組成
d_AlGaN = 20e-9  # AlGaN層厚さ [m]
eps_r = 9.5  # AlGaNの相対誘電率
m_eff = 0.2 * m_e  # 電子有効質量 [kg]

# 分極電荷密度（自発分極 + 圧電分極）
# 例：Al組成0.3のとき ≈ 0.03 C/m²（参考値、論文や実験値により調整推奨）
sigma_pol = 0.03 / (1e-4)**2  # C/m² = 0.03 C/cm² を m²換算

# -------------------------
# 電界・ポテンシャル・2DEG密度計算
# -------------------------
# AlGaN層中の電界 [V/m]
E_field = sigma_pol / (eps_r * epsilon_0)

# 三角井戸ポテンシャル近似による基底状態エネルギー（J）
E1 = ( (9 * np.pi / 8)**(2/3) * (hbar**2 * e * E_field)**(2/3) ) / (2 * m_eff)

# 2DEG密度（シートキャリア密度）[m⁻²] → [cm⁻²] に変換
n_2DEG_m2 = (2 * m_eff * E1) / (np.pi * hbar**2)  # 単位: [1/m²]
n_2DEG_cm2 = n_2DEG_m2 * 1e-4  # 単位: [1/cm²]

# -------------------------
# 結果表示
# -------------------------
print(f"【AlGaN/GaN 2DEG 計算】")
print(f"Al組成 x = {x_Al}")
print(f"AlGaN厚さ = {d_AlGaN * 1e9:.1f} nm")
print(f"分極電荷密度 = {sigma_pol:.2e} C/m²")
print(f"AlGaN中の電界 = {E_field:.2e} V/m")
print(f"基底準位 E1 ≈ {E1/e:.3f} eV")
print(f"→ 推定される2DEG密度 ≈ {n_2DEG_cm2:.2e} cm⁻²")



from sympy import symbols, Eq, solve

# 記号定義
x, y, z = symbols('x y z')

# 式の定義（好きに変更可能）
eq1 = Eq(x + 2*y + z, 4)
eq2 = Eq(3*x - y + 2*z, 7)

# z = 1〜100まで変化
for z_val in range(1, 101):
    # zに値を代入した式を作成
    eq1_sub = eq1.subs(z, z_val)
    eq2_sub = eq2.subs(z, z_val)

    # xとyを解く
    sol = solve((eq1_sub, eq2_sub), (x, y))

    # 結果表示
    print(f"z = {z_val} → x = {sol[x]}, y = {sol[y]}")

import numpy as np
from scipy.constants import epsilon_0, e, hbar, m_e

# -------------------------
# パラメータ設定
# -------------------------
# 材料パラメータ（例：Al₀.₃Ga₀.₇N/GaN構造）
x_Al = 0.3  # Al組成
d_AlGaN = 20e-9  # AlGaN層厚さ [m]
eps_r = 9.5  # AlGaNの相対誘電率
m_eff = 0.2 * m_e  # 電子有効質量 [kg]

# 分極電荷密度（自発分極 + 圧電分極）
# 例：Al組成0.3のとき ≈ 0.03 C/m²（参考値、論文や実験値により調整推奨）
sigma_pol = 0.03 / (1e-4)**2  # C/m² = 0.03 C/cm² を m²換算

# -------------------------
# 電界・ポテンシャル・2DEG密度計算
# -------------------------
# AlGaN層中の電界 [V/m]
E_field = sigma_pol / (eps_r * epsilon_0)

# 三角井戸ポテンシャル近似による基底状態エネルギー（J）
E1 = ( (9 * np.pi / 8)**(2/3) * (hbar**2 * e * E_field)**(2/3) ) / (2 * m_eff)

# 2DEG密度（シートキャリア密度）[m⁻²] → [cm⁻²] に変換
n_2DEG_m2 = (2 * m_eff * E1) / (np.pi * hbar**2)  # 単位: [1/m²]
n_2DEG_cm2 = n_2DEG_m2 * 1e-4  # 単位: [1/cm²]

# -------------------------
# 結果表示
# -------------------------
print(f"【AlGaN/GaN 2DEG 計算】")
print(f"Al組成 x = {x_Al}")
print(f"AlGaN厚さ = {d_AlGaN * 1e9:.1f} nm")
print(f"分極電荷密度 = {sigma_pol:.2e} C/m²")
print(f"AlGaN中の電界 = {E_field:.2e} V/m")
print(f"基底準位 E1 ≈ {E1/e:.3f} eV")
print(f"→ 推定される2DEG密度 ≈ {n_2DEG_cm2:.2e} cm⁻²")

import numpy as np
from scipy.constants import epsilon_0, e, hbar, m_e

# -------------------------
# パラメータ設定
# -------------------------
# 材料パラメータ（例：Al₀.₃Ga₀.₇N/GaN構造）
x_Al = 0.3  # Al組成
d_AlGaN = 20e-9  # AlGaN層厚さ [m]
eps_r = 9.5  # AlGaNの相対誘電率
m_eff = 0.2 * m_e  # 電子有効質量 [kg]

# 分極電荷密度（C/m²） ← 正しい換算！
sigma_pol_cm2 = 0.03  # [C/cm²]（仮の値。典型的な値）
sigma_pol = sigma_pol_cm2 * 1e4  # [C/m²] 1 cm² = 1e-4 m² → C/cm² × 10⁴ = C/m²

# -------------------------
# 電界・ポテンシャル・2DEG密度計算
# -------------------------
E_field = sigma_pol / (eps_r * epsilon_0)  # [V/m]

# トライアングルポテンシャルでの基底状態エネルギー（J）
E1 = ((9 * np.pi / 8)**(2/3) * (hbar**2 * e * E_field)**(2/3)) / (2 * m_eff)
E1_eV = E1 / e  # eVに変換

# 2DEG密度（シートキャリア密度）[1/m²] → [1/cm²]
n_2DEG_m2 = (2 * m_eff * E1) / (np.pi * hbar**2)
n_2DEG_cm2 = n_2DEG_m2 * 1e-4  # m² → cm²

# -------------------------
# 結果表示
# -------------------------
print(f"【AlGaN/GaN 2DEG 計算】")
print(f"Al組成 x = {x_Al}")
print(f"AlGaN厚さ = {d_AlGaN * 1e9:.1f} nm")
print(f"分極電荷密度 = {sigma_pol:.2e} C/m²")
print(f"AlGaN中の電界 = {E_field:.2e} V/m")
print(f"基底準位 E1 ≈ {E1_eV:.3f} eV")
print(f"→ 推定される2DEG密度 ≈ {n_2DEG_cm2:.2e} cm⁻²")

import numpy as np
from scipy.constants import epsilon_0, e, hbar, m_e

# -------------------------
# パラメータ設定
# -------------------------
x_Al = 0.3
d_AlGaN = 20e-9  # [m]
eps_r = 9.5
m_eff = 0.2 * m_e

# 正しい分極電荷密度（例: 0.03 C/cm² → C/m²に変換）
sigma_pol_cm2 = 0.03  # [C/cm²]
sigma_pol = sigma_pol_cm2 * 1e-4  # [C/m²] ← ★正しい換算★

# -------------------------
# 電界・基底状態・2DEG密度
# -------------------------
E_field = sigma_pol / (eps_r * epsilon_0)

E1 = ((9 * np.pi / 8)**(2/3) * (hbar**2 * e * E_field)**(2/3)) / (2 * m_eff)
E1_eV = E1 / e

n_2DEG_m2 = (2 * m_eff * E1) / (np.pi * hbar**2)
n_2DEG_cm2 = n_2DEG_m2 * 1e-4

# -------------------------
# 出力
# -------------------------
print(f"【AlGaN/GaN 2DEG 計算】")
print(f"Al組成 x = {x_Al}")
print(f"AlGaN厚さ = {d_AlGaN * 1e9:.1f} nm")
print(f"分極電荷密度 = {sigma_pol:.2e} C/m²")
print(f"AlGaN中の電界 = {E_field:.2e} V/m")
print(f"基底準位 E1 ≈ {E1_eV:.3f} eV")
print(f"→ 推定される2DEG密度 ≈ {n_2DEG_cm2:.2e} cm⁻²")

import numpy as np
from scipy.constants import epsilon_0, e, hbar, m_e

# -------------------------
# パラメータ設定
# -------------------------
x_Al = 0.1
d_AlGaN = 20e-9  # [m]
eps_r = 9.5
m_eff = 0.2 * m_e

# 分極電荷密度：0.03 C/cm² = 300 C/m²
sigma_pol_cm2 = 0.012  # [C/cm²]
sigma_pol = sigma_pol_cm2 * 1e4  # [C/m²] ← 正しい換算！

# -------------------------
# 電界・エネルギー・2DEG密度
# -------------------------
E_field = sigma_pol / (eps_r * epsilon_0)  # [V/m]

# トライアングルポテンシャル近似での基底準位
E1 = ((9 * np.pi / 8)**(2/3) * (hbar**2 * e * E_field)**(2/3)) / (2 * m_eff)
E1_eV = E1 / e  # [eV]

# 2DEG密度 [m⁻²] → [cm⁻²]
n_2DEG_m2 = (2 * m_eff * E1) / (np.pi * hbar**2)
n_2DEG_cm2 = n_2DEG_m2 * 1e-4

# -------------------------
# 結果表示
# -------------------------
print(f"【AlGaN/GaN 2DEG 計算】")
print(f"Al組成 x = {x_Al}")
print(f"AlGaN厚さ = {d_AlGaN * 1e9:.1f} nm")
print(f"分極電荷密度 = {sigma_pol:.2e} C/m²")
print(f"AlGaN中の電界 = {E_field:.2e} V/m")
print(f"基底準位 E1 ≈ {E1_eV:.3f} eV")
print(f"→ 推定される2DEG密度 ≈ {n_2DEG_cm2:.2e} cm⁻²")

import numpy as np
import matplotlib.pyplot as plt
from scipy.constants import epsilon_0, e, hbar, m_e

# -------------------------
# 固定パラメータ設定
# -------------------------
x_Al = 0.3
eps_r = 9.5
m_eff = 0.2 * m_e

# 分極電荷密度（例：Al0.3Ga0.7N）
sigma_pol_cm2 = 0.012  # [C/cm²]
sigma_pol = sigma_pol_cm2 * 1e4  # [C/m²]

# -------------------------
# 膜厚のスイープ [nm] → [m]
# -------------------------
thickness_nm = np.linspace(5, 40, 100)  # 5nm〜40nm
thickness_m = thickness_nm * 1e-9       # 単位変換

# 結果格納用
n_2DEG_list = []

for d in thickness_m:
    # AlGaN層の電界（分極のみ、膜厚には依存しない簡易モデル）
    E_field = sigma_pol / (eps_r * epsilon_0)  # [V/m]

    # トライアングルポテンシャルモデルでの基底準位
    E1 = ((9 * np.pi / 8)**(2/3) * (hbar**2 * e * E_field)**(2/3)) / (2 * m_eff)

    # 2DEG密度計算 [m⁻²] → [cm⁻²]
    n_2DEG_m2 = (2 * m_eff * E1) / (np.pi * hbar**2)
    n_2DEG_cm2 = n_2DEG_m2 * 1e-4

    n_2DEG_list.append(n_2DEG_cm2)

# -------------------------
# グラフ描画
# -------------------------
plt.figure(figsize=(8, 5))
plt.plot(thickness_nm, n_2DEG_list, label=f'Al comp. x = {x_Al}', color='blue')
plt.xlabel('AlGaN thickness (nm)')
plt.ylabel('2DEG density (cm$^{-2}$)')
plt.title('2DEG Density vs AlGaN Thickness')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# 温度範囲
T = np.linspace(50, 500, 500)  # 単位：K

# 各散乱による移動度（簡易モデル）
mu_imp = 1e4 * (T / 300) ** (1.5)           # イオン化不純物散乱（温度上昇で増加）
mu_phonon = 1e4 * (T / 300) ** (-1.8)       # 格子散乱（温度上昇で減少）
mu_surf = np.ones_like(T) * 300            # 表面粗さ（温度依存性なし）
mu_pz = 600 * (T / 300) ** (-1.2)          # ピエゾ電界散乱

# 全体の移動度（マチーソン則）
mu_total = 1 / (1/mu_imp + 1/mu_phonon + 1/mu_surf + 1/mu_pz)

# プロット
plt.figure(figsize=(10, 6))
plt.plot(T, mu_imp, label='Ionized Impurity Scattering', linestyle='--')
plt.plot(T, mu_phonon, label='Phonon Scattering', linestyle='--')
plt.plot(T, mu_surf, label='Surface Roughness Scattering', linestyle='--')
plt.plot(T, mu_pz, label='Piezoelectric Scattering', linestyle='--')
plt.plot(T, mu_total, label='Total Mobility', color='black', linewidth=2)

plt.xlabel('Temperature (K)')
plt.ylabel('Mobility (cm²/Vs)')
plt.title('Temperature Dependence of 2DEG Mobility in AlGaN/AlN/GaN HEMT')
plt.legend()
plt.grid(True)
#plt.ylim(0, 400)  # ← ここを追加plt.yscale('log')
plt.yscale('log')
plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from scipy.constants import epsilon_0, e, hbar, m_e

# -------------------------
# 固定パラメータ
# -------------------------
d_AlGaN = 20e-9  # AlGaN厚さ [m]
eps_r = 9.5
m_eff = 0.2 * m_e

# Al組成範囲
x_vals = np.linspace(0.0, 0.5, 100)
n_2DEG_vals = []

# -------------------------
# Al組成ごとの計算ループ
# -------------------------
for x_Al in x_vals:
    # 分極電荷密度 σ_pol(x) [C/m²]
    # 経験式（Ambacher et al. JAP 2000）：界面での分極電荷
    sigma_pol = -0.034 + 0.057 * x_Al  # [C/m²]

    if sigma_pol < 0:
        n_2DEG_vals.append(0)  # 電荷が負なら2DEGは形成されない
        continue

    # AlGaN層の電界 [V/m]
    E_field = sigma_pol / (eps_r * epsilon_0)

    # トライアングルポテンシャルモデルでの基底準位 [J]
    E1 = ((9 * np.pi / 8)**(2/3) * (hbar**2 * e * E_field)**(2/3)) / (2 * m_eff)

    # 2DEG密度 [m⁻²] → [cm⁻²]
    n_2DEG_m2 = (2 * m_eff * E1) / (np.pi * hbar**2)
    n_2DEG_cm2 = n_2DEG_m2 * 1e-4
    n_2DEG_vals.append(n_2DEG_cm2)

# -------------------------
# グラフ描画
# -------------------------
plt.figure(figsize=(8,5))
plt.plot(x_vals, n_2DEG_vals, color='darkgreen')
plt.xlabel('Al composition (x)')
plt.ylabel('2DEG density (cm$^{-2}$)')
plt.title(f'2DEG Density vs Al Composition (AlGaN thickness = {d_AlGaN*1e9:.0f} nm)')
plt.grid(True)
plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# 温度範囲
T = np.linspace(50, 500, 500)  # 単位：K

# 各散乱による移動度（簡易モデル）
mu_imp = 1e4 * (T / 300) ** (1.5)           # イオン化不純物散乱
mu_phonon = 1e4 * (T / 300) ** (-1.8)       # 格子散乱
mu_surf = np.ones_like(T) * 3000            # 表面粗さ
mu_pz = 6000 * (T / 300) ** (-1.2)          # ピエゾ電界散乱

# 全体の移動度（マチーソン則）
mu_total = 1 / (1/mu_imp + 1/mu_phonon + 1/mu_surf + 1/mu_pz)

# プロット
plt.figure(figsize=(10, 6))
plt.plot(T, mu_imp, label='Ionized Impurity Scattering', linestyle='--')
plt.plot(T, mu_phonon, label='Phonon Scattering', linestyle='--')
plt.plot(T, mu_surf, label='Surface Roughness Scattering', linestyle='--')
plt.plot(T, mu_pz, label='Piezoelectric Scattering', linestyle='--')
plt.plot(T, mu_total, label='Total Mobility', color='black', linewidth=2)

plt.xlabel('Temperature (K)')
plt.ylabel('Mobility (cm²/Vs)')
plt.title('Temperature Dependence of 2DEG Mobility in AlGaN/AlN/GaN HEMT')
plt.ylim(0, 200)  # ← ここを追加
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from scipy.constants import epsilon_0, e, hbar, m_e

# -------------------------
# 定数・パラメータ
# -------------------------
d_AlGaN = 20e-9  # AlGaN厚さ [m]
eps_r = 9.5
m_eff = 0.2 * m_e
P_sp_GaN = -0.034  # [C/m²]

# アルミ組成のスイープ
x_vals = np.linspace(0.0, 0.5, 100)
n_2DEG_vals = []

for x in x_vals:
    # 自発分極 [C/m²]
    P_sp_AlGaN = -0.090 * x - 0.034 * (1 - x)

    # 圧電分極 [C/m²]（簡易モデル、成長ひずみありを仮定）
    P_pz_AlGaN = 0.052 * x

    # 分極電荷密度 = 界面での分極差
    sigma_pol = (P_sp_AlGaN + P_pz_AlGaN) - P_sp_GaN  # [C/m²]

    # AlGaN層中の電界
    E_field = sigma_pol / (eps_r * epsilon_0)  # [V/m]

    # トライアングルポテンシャルモデルによる基底準位
    E1 = ((9 * np.pi / 8)**(2/3) * (hbar**2 * e * E_field)**(2/3)) / (2 * m_eff)

    # 2DEG密度 [m⁻²] → [cm⁻²]
    n_2DEG_m2 = (2 * m_eff * E1) / (np.pi * hbar**2)
    n_2DEG_cm2 = n_2DEG_m2 * 1e-4
    n_2DEG_vals.append(n_2DEG_cm2)

# -------------------------
# グラフ描画
# -------------------------
plt.figure(figsize=(8,5))
plt.plot(x_vals, n_2DEG_vals, color='blue')
plt.xlabel('Al composition (x)')
plt.ylabel('2DEG density (cm$^{-2}$)')
plt.title(f'2DEG Density vs Al Composition (AlGaN thickness = {d_AlGaN*1e9:.0f} nm)')
plt.grid(True)
plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from scipy.constants import epsilon_0, e, hbar, m_e

# -------------------------
# 定数・パラメータ
# -------------------------
d_AlGaN = 20e-9  # AlGaN厚さ [m]
eps_r = 9.5
m_eff = 0.2 * m_e
P_sp_GaN = -0.034  # [C/m²]

# アルミ組成のスイープ
x_vals = np.linspace(0.0, 0.5, 100)
n_2DEG_vals = []

for x in x_vals:
    # 自発分極 [C/m²]
    P_sp_AlGaN = -0.090 * x - 0.034 * (1 - x)

    # 圧電分極 [C/m²]（簡易モデル、成長ひずみありを仮定）
    P_pz_AlGaN = 0.052 * x

    # 分極電荷密度 = 界面での分極差
    sigma_pol = (P_sp_AlGaN + P_pz_AlGaN) - P_sp_GaN  # [C/m²]

    # AlGaN層中の電界
    E_field = sigma_pol / (eps_r * epsilon_0)  # [V/m]

    if E_field <= 0:
        n_2DEG_vals.append(0)
        continue

    # トライアングルポテンシャルモデルによる基底準位
    E1 = ((9 * np.pi / 8)**(2/3) * (hbar**2 * e * E_field)**(2/3)) / (2 * m_eff)

    # 2DEG密度 [m⁻²] → [cm⁻²]
    n_2DEG_m2 = (2 * m_eff * E1) / (np.pi * hbar**2)
    n_2DEG_cm2 = n_2DEG_m2 * 1e-4
    n_2DEG_vals.append(n_2DEG_cm2)

# -------------------------
# グラフ描画
# -------------------------
plt.figure(figsize=(8, 5))
plt.plot(x_vals, n_2DEG_vals, color='blue')
plt.xlabel('Al composition (x)')
plt.ylabel('2DEG density (cm$^{-2}$)')
plt.title(f'2DEG Density vs Al Composition (AlGaN thickness = {d_AlGaN*1e9:.0f} nm)')
plt.grid(True)
plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import root_scalar

# 定数定義（単位はメートル）
cGaN = 5.189e-10
cInN = 5.760e-10
aGaN = 3.185e-10
aInN = 3.584e-10
aAlN = 3.112e-10
cAlN = 4.982e-10
nu_GaN = 0.271
nu_AlN = 0.266

# 各種関数定義
def da(xg):
    return xg * (aGaN - aAlN)

def f(xg):
    return da(xg) / aAlN

def b(xg):
    return aAlN + xg * (aGaN - aAlN)

def nu(xg):
    return nu_GaN - xg * (nu_GaN - nu_AlN)

def F1(hc, xg):
    term1 = b(xg) / (2 * np.pi * f(xg))
    term2 = 1 / (1 + nu(xg))
    term3 = np.log(hc / b(xg)) + 1
    return term1 * term2 * term3 - hc

# 結果格納用リスト
q1_list = []
q2_list = []

# メインループ（xg = 0.01 * n）
for n in range(1, 101):  # 1 〜 100
    xg = 0.01 * n
    try:
        sol = root_scalar(F1, args=(xg,), bracket=[1e-12, 1e-7], method='brentq')
        if sol.converged:
            hc = sol.root
            q1_list.append(1 - xg)
            q2_list.append(hc * 1e9)  # 単位：nm
    except ValueError:
        # 解が見つからない場合
        continue

# データをNumPy配列に変換
A = np.column_stack((q1_list, q2_list))

# プロット（対数スケール）
plt.figure(figsize=(6, 4))
plt.plot(q1_list, q2_list, marker='o')
plt.xlim(0, 1)
plt.yscale('log')
plt.ylim(1, 1000)
plt.xlabel('1 - xg')
plt.ylabel('Critical thickness (nm)')
plt.title('Critical thickness vs. relaxation rate')
plt.grid(True)
plt.tight_layout()
plt.show()

# データの保存
np.savetxt("Thickness.dat", A, fmt="%.6f", header="1 - xg\tThickness [nm]")



import numpy as np
import matplotlib.pyplot as plt

# 定数
R = 8.314  # J/mol/K
T = 1273  # 成長温度 [K]
k_conversion = 1.0  # GaClへの変換効率（仮定）
surface_area = 1.0  # 成長面積 [cm^2]（仮定）

# HCl流量 [mol/min] の範囲を定義
hcl_flow_rates = np.linspace(0.01, 0.5, 100)  # 0.01〜0.5 mol/min

# GaCl生成量（＝GaN成長に寄与する）[mol/min]
ga_cl_production = k_conversion * hcl_flow_rates  # 仮定：GaCl = HCl（1対1）

# GaNのモル質量と密度
molar_mass_gan = 83.73  # g/mol
density_gan = 6.15  # g/cm^3

# 成長速度 [μm/min] に換算
gan_growth_rate = (ga_cl_production * molar_mass_gan / density_gan) * 1e4 / surface_area

# グラフ表示
plt.plot(hcl_flow_rates, gan_growth_rate, label='GaN growth rate')
plt.xlabel('HCl Flow Rate [mol/min]')
plt.ylabel('GaN Growth Rate [μm/min]')
plt.title('GaN Growth Rate vs HCl Flow Rate in HVPE')
plt.grid(True)
plt.legend()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# 定数
R = 8.314  # J/mol/K
hcl_flow_rate = 0.1  # mol/min（一定）

# 温度範囲 [K]
temperatures = np.linspace(900, 1400, 200)

# 熱力学データ（近似）
# Ga + HCl → GaCl + 0.5H2（吸熱反応）
delta_H1 = 79000  # J/mol
delta_S1 = 108    # J/mol/K

# GaCl + NH3 → GaN + HCl + H2（発熱反応）
delta_H2 = -120000  # J/mol
delta_S2 = -240     # J/mol/K

# ΔG, Kp for both reactions
delta_G1 = delta_H1 - temperatures * delta_S1
Kp1 = np.exp(-delta_G1 / (R * temperatures))  # GaCl生成：温度上昇で増加

delta_G2 = delta_H2 - temperatures * delta_S2
Kp2 = np.exp(-delta_G2 / (R * temperatures))  # GaN生成：温度上昇で減少

# 成長速度 ∝ GaCl生成 × GaN形成
combined_reaction_rate = hcl_flow_rate * Kp1 * Kp2

# GaN成長速度 [μm/min]
molar_mass_gan = 83.73  # g/mol
density_gan = 6.15  # g/cm^3
surface_area = 1.0  # cm^2

gan_growth_rate = (combined_reaction_rate * molar_mass_gan / density_gan) * 1e4 / surface_area

# プロット
plt.plot(temperatures, gan_growth_rate)
plt.xlabel('Temperature [K]')
plt.ylabel('GaN Growth Rate [μm/min]')
plt.title('GaN Growth Rate vs Temperature (HCl fixed at 0.1 mol/min)')
plt.grid(True)

# ピーク温度の表示
peak_index = np.argmax(gan_growth_rate)
peak_temp = temperatures[peak_index]
peak_rate = gan_growth_rate[peak_index]
plt.axvline(x=peak_temp, color='r', linestyle='--', label=f'Peak: {peak_temp:.0f} K')
plt.legend()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# 定数
R = 8.314  # J/mol/K
hcl_flow_rate = 0.1  # mol/min（一定）

# 温度範囲：100°C = 373K 〜 1400K
temperatures = np.linspace(373, 1400, 300)

# 熱力学データ（近似）
# Ga + HCl → GaCl + 0.5H2（吸熱反応）
delta_H1 = 79000  # J/mol
delta_S1 = 108    # J/mol/K

# GaCl + NH3 → GaN + HCl + H2（発熱反応）
delta_H2 = -120000  # J/mol
delta_S2 = -240     # J/mol/K

# ΔG, Kp for both reactions
delta_G1 = delta_H1 - temperatures * delta_S1
Kp1 = np.exp(-delta_G1 / (R * temperatures))  # GaCl生成：温度上昇で増加

delta_G2 = delta_H2 - temperatures * delta_S2
Kp2 = np.exp(-delta_G2 / (R * temperatures))  # GaN生成：温度上昇で減少

# 成長速度 ∝ GaCl生成 × GaN形成
combined_reaction_rate = hcl_flow_rate * Kp1 * Kp2

# GaN成長速度 [μm/min]
molar_mass_gan = 83.73  # g/mol
density_gan = 6.15  # g/cm^3
surface_area = 1.0  # cm^2

gan_growth_rate = (combined_reaction_rate * molar_mass_gan / density_gan) * 1e4 / surface_area

# プロット
plt.plot(temperatures, gan_growth_rate)
plt.xlabel('Temperature [K]')
plt.ylabel('GaN Growth Rate [μm/min]')
plt.title('GaN Growth Rate vs Temperature (100°C to 1400K, HCl fixed at 0.1 mol/min)')
plt.grid(True)

# ピーク温度の表示
peak_index = np.argmax(gan_growth_rate)
peak_temp = temperatures[peak_index]
peak_rate = gan_growth_rate[peak_index]
plt.axvline(x=peak_temp, color='r', linestyle='--', label=f'Peak: {peak_temp:.0f} K')
plt.legend()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# 定数
R = 8.314  # J/mol/K
hcl_flow_rate = 0.1  # mol/min（一定）

# 温度範囲：100°C = 373K 〜 1400K
temperatures = np.linspace(373, 1400, 300)

# 熱力学データ（修正後）
# Ga + HCl → GaCl + 0.5H2（吸熱反応）
delta_H1 = 79000   # J/mol
delta_S1 = 108     # J/mol/K

# GaCl + NH3 → GaN + HCl + H2（発熱反応, 調整済み）
delta_H2 = -85000   # J/mol ← 修正
delta_S2 = -180     # J/mol/K ← 修正

# ΔG, Kp for both reactions
delta_G1 = delta_H1 - temperatures * delta_S1
Kp1 = np.exp(-delta_G1 / (R * temperatures))  # GaCl生成：温度上昇で増加

delta_G2 = delta_H2 - temperatures * delta_S2
Kp2 = np.exp(-delta_G2 / (R * temperatures))  # GaN生成：温度上昇で減少（調整）

# 成長速度 ∝ GaCl生成 × GaN形成
combined_reaction_rate = hcl_flow_rate * Kp1 * Kp2

# GaN成長速度 [μm/min]
molar_mass_gan = 83.73  # g/mol
density_gan = 6.15  # g/cm^3
surface_area = 1.0  # cm^2

gan_growth_rate = (combined_reaction_rate * molar_mass_gan / density_gan) * 1e4 / surface_area

# プロット
plt.plot(temperatures, gan_growth_rate)
plt.xlabel('Temperature [K]')
plt.ylabel('GaN Growth Rate [μm/min]')
plt.title('GaN Growth Rate vs Temperature (HCl fixed at 0.1 mol/min)')
plt.grid(True)

# ピーク温度の表示
peak_index = np.argmax(gan_growth_rate)
peak_temp = temperatures[peak_index]
peak_rate = gan_growth_rate[peak_index]
plt.axvline(x=peak_temp, color='r', linestyle='--', label=f'Peak: {peak_temp:.0f} K')
plt.legend()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# 定数
R = 8.314  # J/mol/K
A = 1e6    # 前因子（μm/min）
Ea = 170000  # J/mol, 活性化エネルギー

# GaN生成反応の熱力学パラメータ（発熱反応）
delta_H = -85000   # J/mol
delta_S = -180     # J/mol/K

# 温度範囲：100°C = 373K ～ 1400K
temperatures = np.linspace(373, 1400, 300)

# 平衡定数
delta_G = delta_H - temperatures * delta_S
K_eq = np.exp(-delta_G / (R * temperatures))

# Arrhenius項（速度論）
rate_constant = A * np.exp(-Ea / (R * temperatures))

# 成長速度（反応速度 × 平衡定数）
growth_rate = rate_constant * K_eq

# プロット
plt.plot(temperatures, growth_rate)
plt.xlabel('Temperature [K]')
plt.ylabel('GaN Growth Rate [μm/min]')
plt.title('GaN Growth Rate vs Temperature (with kinetics + equilibrium)')
plt.grid(True)

# ピーク温度の表示
peak_index = np.argmax(growth_rate)
peak_temp = temperatures[peak_index]
plt.axvline(x=peak_temp, color='r', linestyle='--', label=f'Peak: {peak_temp:.0f} K')
plt.legend()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# 温度範囲：100°C = 373K ～ 1400K
temperatures = np.linspace(373, 1400, 300)

# 経験式パラメータ
R_max = 10.0         # μm/min（最大成長速度）
T_peak = 1273        # K（1000℃）
sigma = 120          # K（幅）

# 経験式（ガウス型）
growth_rate = R_max * np.exp(-((temperatures - T_peak)**2) / (2 * sigma**2))

# プロット
plt.plot(temperatures, growth_rate, label='Empirical Gaussian model')
plt.xlabel('Temperature [K]')
plt.ylabel('GaN Growth Rate [μm/min]')
plt.title('GaN Growth Rate vs Temperature (Peak at 1000°C)')
plt.grid(True)

# ピーク表示
plt.axvline(x=T_peak, color='r', linestyle='--', label=f'Peak: {T_peak} K (1000°C)')
plt.legend()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

R = 8.314  # J/mol/K
temperatures = np.linspace(373, 1400, 300)

# 熱力学（GaN生成反応）
delta_H = -85000  # J/mol
delta_S = -180    # J/mol/K
delta_G = delta_H - temperatures * delta_S
K_eq = np.exp(-delta_G / (R * temperatures))

# 速度論（仮定: GaN生成の表面反応律速）
Ea = 170000  # J/mol
A = 1e6      # μm/min
rate_constant = A * np.exp(-Ea / (R * temperatures))

# 成長速度 = 平衡定数 × 反応速度
growth_rate = K_eq * rate_constant

# プロット
plt.plot(temperatures, growth_rate)
plt.xlabel('Temperature [K]')
plt.ylabel('Growth Rate [μm/min]')
plt.title('GaN Growth Rate vs Temperature (Thermo + Kinetics)')
plt.grid(True)
plt.show()

import numpy as np
import matplotlib.pyplot as plt

R = 8.314  # J/mol/K
T = np.linspace(373, 1400, 400)  # 温度範囲（100℃～1127℃）

# 各律速のモデル
# 1. 表面反応律速（低温）
Ea = 150000  # J/mol
A = 1e10
r_kinetic = A * np.exp(-Ea / (R * T))

# 2. 拡散律速（上限で一定）
r_diffusion = np.full_like(T, 10.0)  # μm/min

# 3. 熱力学律速（高温で逆反応）
delta_H = -85000  # J/mol
delta_S = -180
delta_G = delta_H - T * delta_S
Kp = np.exp(-delta_G / (R * T))
r_thermo = Kp * 1e3  # スケーリング

# 成長速度：最も律速なものが支配
r_total = np.minimum(np.minimum(r_kinetic, r_diffusion), r_thermo)

# グラフ
plt.plot(T, r_kinetic, '--', label='Kinetics control')
plt.plot(T, r_diffusion, '--', label='Diffusion limit')
plt.plot(T, r_thermo, '--', label='Thermodynamics limit')
plt.plot(T, r_total, linewidth=2.5, label='Total growth rate')

plt.xlabel('Substrate temperature [K]')
plt.ylabel('Growth rate [μm/min]')
plt.title('HVPE GaN Growth Rate vs Temperature (3-regime model)')
plt.grid(True)
plt.legend()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

R = 8.314  # J/mol/K
T = np.linspace(800, 1400, 400)  # 温度範囲（100℃～1127℃）

# 各律速のモデル
# 1. 表面反応律速（低温）
Ea = 150000  # J/mol
A = 1e10
r_kinetic = A * np.exp(-Ea / (R * T))

# 2. 拡散律速（上限で一定）
r_diffusion = np.full_like(T, 10.0)  # μm/min

# 3. 熱力学律速（高温で逆反応）
delta_H = -85000  # J/mol
delta_S = -180
delta_G = delta_H - T * delta_S
Kp = np.exp(-delta_G / (R * T))
r_thermo = Kp * 1e3  # スケーリング

# 成長速度：最も律速なものが支配
r_total = np.minimum(np.minimum(r_kinetic, r_diffusion), r_thermo)

# グラフ
plt.plot(T, r_kinetic, '--', label='Kinetics control')
plt.plot(T, r_diffusion, '--', label='Diffusion limit')
plt.plot(T, r_thermo, '--', label='Thermodynamics limit')
plt.plot(T, r_total, linewidth=2.5, label='Total growth rate')

plt.xlabel('Substrate temperature [K]')
plt.ylabel('Growth rate [μm/min]')
plt.title('HVPE GaN Growth Rate vs Temperature (3-regime model)')
plt.grid(True)
plt.legend()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# 定数（単位系は自然単位系: ℏ = 1, 2m = 1）
hbar = 1
m = 0.5  # 2m=1より
a = 1.0  # 格子定数
P = 10.0  # ポテンシャル強度（無次元）

# エネルギー範囲の設定
E_vals = np.linspace(0.01, 100, 1000)  # エネルギーのスキャン範囲
k_vals = []  # 許されるkの値を格納

for E in E_vals:
    q = np.sqrt(2 * m * E) / hbar
    lhs = np.cos(q * a) + P / (q * a) * np.sin(q * a)
    if np.abs(lhs) <= 1:
        k = np.arccos(lhs) / a
        k_vals.append([E, k])
        # 負のkも加える（対称性）
        k_vals.append([E, -k])

# 配列に変換してプロット
k_vals = np.array(k_vals)
plt.figure(figsize=(8, 6))
plt.scatter(k_vals[:, 1], k_vals[:, 0], s=1, color='blue')
plt.xlabel("Wavevector k")
plt.ylabel("Energy E")
plt.title("Kronig-Penney Model: E-k Dispersion")
plt.grid(True)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from scipy.constants import hbar, e, m_e
from scipy.linalg import eigh_tridiagonal

# パラメータ
me_eff = 0.2 * m_e   # 電子の有効質量
mh_eff = 1.0 * m_e   # 正孔の有効質量
F = 1e7              # 分極電場 [V/m]（例として1e7 V/m = 100 kV/cm）
L_b = 5e-9           # 障壁厚 [m]（固定）

# 井戸厚の範囲
well_thicknesses = np.linspace(2e-9, 10e-9, 50)
overlaps = []

# 数値計算用格子
N = 1000
L_total = 30e-9
z = np.linspace(0, L_total, N)
dz = z[1] - z[0]

for L_w in well_thicknesses:
    # ポテンシャルプロファイル（電子と正孔で反対向き）
    V_e = np.zeros_like(z)
    V_h = np.zeros_like(z)

    # InGaN井戸領域（中央部）
    well_start = L_total/2 - L_w/2
    well_end = L_total/2 + L_w/2
    for i in range(N):
        if well_start <= z[i] <= well_end:
            V_e[i] = -e * F * (z[i] - well_start)   # 線形電場（電子）
            V_h[i] = +e * F * (z[i] - well_start)   # 線形電場（正孔）
        else:
            V_e[i] = 0.5   # 高障壁 [eV]
            V_h[i] = 0.5

    # 電子・正孔のシュレディンガー方程式を数値的に解く（1次元）
    def solve_schrodinger(V, mass):
        kin_const = hbar**2 / (2 * mass * dz**2)
        main_diag = 2 * kin_const + V
        off_diag = -kin_const * np.ones(N-1)
        energies, wavefuncs = eigh_tridiagonal(main_diag, off_diag)
        psi = wavefuncs[:, 0] / np.sqrt(np.sum(np.abs(wavefuncs[:, 0])**2) * dz)
        return energies[0], psi

    E_e, psi_e = solve_schrodinger(V_e, me_eff)
    E_h, psi_h = solve_schrodinger(V_h, mh_eff)

    # 重なり積分 |∫ψe * ψh dz|^2
    overlap = np.abs(np.sum(psi_e * psi_h) * dz)**2
    overlaps.append(overlap)

# プロット
plt.figure(figsize=(8, 6))
plt.plot(well_thicknesses * 1e9, overlaps, marker='o')
plt.xlabel("InGaN井戸厚 [nm]")
plt.ylabel("波動関数の重なり積分 $|\\langle \psi_e | \psi_h \\rangle|^2$")
plt.title("GaN/InGaN量子井戸における重なり積分 vs 井戸厚")
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import matplotlib as mpl
import numpy as np
import matplotlib.pyplot as plt
from scipy.constants import hbar, e, m_e
from scipy.linalg import eigh_tridiagonal

# パラメータ
me_eff = 0.2 * m_e   # 電子の有効質量
mh_eff = 1.0 * m_e   # 正孔の有効質量
F = 1e7              # 分極電場 [V/m]（例として1e7 V/m = 100 kV/cm）
L_b = 5e-9           # 障壁厚 [m]（固定）

# 井戸厚の範囲
well_thicknesses = np.linspace(2e-9, 10e-9, 50)
overlaps = []

# 数値計算用格子
N = 1000
L_total = 30e-9
z = np.linspace(0, L_total, N)
dz = z[1] - z[0]

for L_w in well_thicknesses:
    # ポテンシャルプロファイル（電子と正孔で反対向き）
    V_e = np.zeros_like(z)
    V_h = np.zeros_like(z)

    # InGaN井戸領域（中央部）
    well_start = L_total/2 - L_w/2
    well_end = L_total/2 + L_w/2
    for i in range(N):
        if well_start <= z[i] <= well_end:
            V_e[i] = -e * F * (z[i] - well_start)   # 線形電場（電子）
            V_h[i] = +e * F * (z[i] - well_start)   # 線形電場（正孔）
        else:
            V_e[i] = 0.5   # 高障壁 [eV]
            V_h[i] = 0.5

    # 電子・正孔のシュレディンガー方程式を数値的に解く（1次元）
    def solve_schrodinger(V, mass):
        kin_const = hbar**2 / (2 * mass * dz**2)
        main_diag = 2 * kin_const + V
        off_diag = -kin_const * np.ones(N-1)
        energies, wavefuncs = eigh_tridiagonal(main_diag, off_diag)
        psi = wavefuncs[:, 0] / np.sqrt(np.sum(np.abs(wavefuncs[:, 0])**2) * dz)
        return energies[0], psi

    E_e, psi_e = solve_schrodinger(V_e, me_eff)
    E_h, psi_h = solve_schrodinger(V_h, mh_eff)

    # 重なり積分 |∫ψe * ψh dz|^2
    overlap = np.abs(np.sum(psi_e * psi_h) * dz)**2
    overlaps.append(overlap)

# プロット
mpl.rcParams['font.family'] = 'IPAexGothic'  # 必要に応じて他の日本語フォントに変更

plt.figure(figsize=(8, 6))
plt.plot(well_thicknesses * 1e9, overlaps, marker='o')
plt.xlabel("InGaN井戸厚 [nm]")
plt.ylabel("波動関数の重なり積分 |⟨ψe|ψh⟩|²")
plt.title("GaN/InGaN量子井戸における波動関数の重なり積分 vs 井戸厚")
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import matplotlib as mpl
import numpy as np
import matplotlib.pyplot as plt
from scipy.constants import hbar, e, m_e
from scipy.linalg import eigh_tridiagonal

# パラメータ
me_eff = 0.2 * m_e   # 電子の有効質量
mh_eff = 1.0 * m_e   # 正孔の有効質量
F = 1e7              # 分極電場 [V/m]（例として1e7 V/m = 100 kV/cm）
L_b = 5e-9           # 障壁厚 [m]（固定）

# 井戸厚の範囲
well_thicknesses = np.linspace(2e-9, 10e-9, 50)
overlaps = []

# 数値計算用格子
N = 1000
L_total = 30e-9
z = np.linspace(0, L_total, N)
dz = z[1] - z[0]

for L_w in well_thicknesses:
    # ポテンシャルプロファイル（電子と正孔で反対向き）
    V_e = np.zeros_like(z)
    V_h = np.zeros_like(z)

    # InGaN井戸領域（中央部）
    well_start = L_total/2 - L_w/2
    well_end = L_total/2 + L_w/2
    for i in range(N):
        if well_start <= z[i] <= well_end:
            V_e[i] = -e * F * (z[i] - well_start)   # 線形電場（電子）
            V_h[i] = +e * F * (z[i] - well_start)   # 線形電場（正孔）
        else:
            V_e[i] = 0.5   # 高障壁 [eV]
            V_h[i] = 0.5

    # 電子・正孔のシュレディンガー方程式を数値的に解く（1次元）
    def solve_schrodinger(V, mass):
        kin_const = hbar**2 / (2 * mass * dz**2)
        main_diag = 2 * kin_const + V
        off_diag = -kin_const * np.ones(N-1)
        energies, wavefuncs = eigh_tridiagonal(main_diag, off_diag)
        psi = wavefuncs[:, 0] / np.sqrt(np.sum(np.abs(wavefuncs[:, 0])**2) * dz)
        return energies[0], psi

    E_e, psi_e = solve_schrodinger(V_e, me_eff)
    E_h, psi_h = solve_schrodinger(V_h, mh_eff)

    # 重なり積分 |∫ψe * ψh dz|^2
    overlap = np.abs(np.sum(psi_e * psi_h) * dz)**2
    overlaps.append(overlap)

# プロット
mpl.rcParams['font.family'] = 'IPAexGothic'  # 必要に応じて他の日本語フォントに変更



plt.figure(figsize=(8, 6))
plt.plot(well_thicknesses * 1e9, overlaps, marker='o')
plt.xlabel("Well width [nm]")
plt.ylabel("Wavefunction overlap |⟨ψe|ψh⟩|²")
plt.title("Wavefunction overlap in GaN/InGaN QW vs well width")
plt.grid(True)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from scipy.constants import hbar, e, m_e
from scipy.linalg import eigh_tridiagonal

# パラメータ
me_eff = 0.2 * m_e   # 電子の有効質量 [kg]
mh_eff = 1.0 * m_e   # 正孔の有効質量 [kg]
F = 1e7              # 分極電場 [V/m]
L_b = 5e-9           # 障壁厚 [m]（今回は使わない）

# 井戸厚の範囲（2〜10 nm）
well_thicknesses = np.linspace(2e-9, 10e-9, 50)
overlaps = []

# 計算格子の設定
N = 1000
L_total = 30e-9  # 全体の構造長 [m]
z = np.linspace(0, L_total, N)
dz = z[1] - z[0]

for L_w in well_thicknesses:
    # 初期ポテンシャル設定（障壁部分） [J]
    V_e = np.full(N, 0.5 * e)  # 電子ポテンシャル
    V_h = np.full(N, 0.5 * e)  # 正孔ポテンシャル

    # 井戸領域（中央）
    well_start = L_total / 2 - L_w / 2
    well_end = L_total / 2 + L_w / 2
    in_well = (z >= well_start) & (z <= well_end)

    # 線形ポテンシャル（分極電場の影響） [J]
    V_e[in_well] = -e * F * (z[in_well] - well_start)  # 電子用
    V_h[in_well] = +e * F * (z[in_well] - well_start)  # 正孔用

    # シュレディンガー方程式を解く
    def solve_schrodinger(V, mass):
        kin_const = hbar**2 / (2 * mass * dz**2)
        main_diag = 2 * kin_const + V
        off_diag = -kin_const * np.ones(N - 1)
        energies, wavefuncs = eigh_tridiagonal(main_diag, off_diag)
        psi = wavefuncs[:, 0]
        norm = np.sqrt(np.sum(np.abs(psi)**2) * dz)
        return energies[0], psi / norm

    E_e, psi_e = solve_schrodinger(V_e, me_eff)
    E_h, psi_h = solve_schrodinger(V_h, mh_eff)

    # 重なり積分 |⟨ψe|ψh⟩|^2
    overlap = np.abs(np.sum(np.conj(psi_e) * psi_h) * dz)**2
    overlaps.append(overlap)

# プロット
plt.figure(figsize=(8, 6))
plt.plot(well_thicknesses * 1e9, overlaps, marker='o')
plt.xlabel("Well width [nm]")
plt.ylabel("Wavefunction overlap |⟨ψe|ψh⟩|²")
plt.title("Wavefunction overlap in GaN/InGaN QW vs well width")
plt.grid(True)
plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import root_scalar

# 定数定義（単位はメートル）
cGaN = 5.189e-10
cInN = 5.760e-10
aGaN = 3.185e-10
aInN = 3.584e-10
aAlN = 3.112e-10
cAlN = 4.982e-10
nu_GaN = 0.271
nu_AlN = 0.266

# 各種関数定義
def da(xg):
    return xg * (aGaN - aAlN)

def f(xg):
    return da(xg) / aAlN

def b(xg):
    return aAlN + xg * (aGaN - aAlN)

def nu(xg):
    return nu_GaN - xg * (nu_GaN - nu_AlN)

def F1(hc, xg):
    term1 = b(xg) / (2 * np.pi * f(xg))
    term2 = 1 / (1 + nu(xg))
    term3 = np.log(hc / b(xg)) + 1
    return term1 * term2 * term3 - hc

# 結果格納用リスト
q1_list = []
q2_list = []

# メインループ（xg = 0.01 * n）
for n in range(1, 101):  # 1 〜 100
    xg = 0.01 * n
    try:
        sol = root_scalar(F1, args=(xg,), bracket=[1e-12, 1e-7], method='brentq')
        if sol.converged:
            hc = sol.root
            q1_list.append(1 - xg)
            q2_list.append(hc * 1e9)  # 単位：nm
    except ValueError:
        # 解が見つからない場合
        continue

# データをNumPy配列に変換
A = np.column_stack((q1_list, q2_list))

# プロット（対数スケール）
plt.figure(figsize=(6, 4))
plt.plot(q1_list, q2_list, marker='o')
plt.xlim(0, 1)
plt.yscale('log')
plt.ylim(1, 1000)
plt.xlabel('1 - xg')
plt.ylabel('Critical thickness (nm)')
plt.title('Critical thickness vs. relaxation rate')
plt.grid(True)
plt.tight_layout()
plt.show()

# データの保存
np.savetxt("Thickness.dat", A, fmt="%.6f", header="1 - xg\tThickness [nm]")



for n in range(1, 12):  # xg=0.01〜0.11
    xg = 0.01 * n
    bx = b(xg)
    hc_min = bx * 1.01
    hc_max = 1e-7
    F_min = F1(hc_min, xg)
    F_max = F1(hc_max, xg)
    print(f"xg={xg:.2f}, b(xg)={bx:.3e}, hc range=({hc_min:.3e}, {hc_max:.3e})")
    print(f"  F(hc_min)={F_min:.3e}, F(hc_max)={F_max:.3e}")

import matplotlib.pyplot as plt

xg = 0.01
hc_vals = np.logspace(np.log10(b(xg)*1.01), -7, 200)
F_vals = [F1(hc, xg) for hc in hc_vals]

plt.plot(hc_vals, F_vals)
plt.axhline(0, color='gray', linestyle='--')
plt.xscale('log')
plt.xlabel("hc (m)")
plt.ylabel("F1(hc)")
plt.title(f"F1(hc) vs hc for xg = {xg}")
plt.grid(True, which='both')
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import root_scalar

# 定数定義（単位：m）
aGaN = 3.185e-10
aAlN = 3.112e-10
nu_GaN = 0.271
nu_AlN = 0.266

# 関数定義
def da(xg):
    return xg * (aGaN - aAlN)

def f(xg):
    return da(xg) / aAlN

def b(xg):
    return aAlN + xg * (aGaN - aAlN)

def nu(xg):
    return nu_GaN - xg * (nu_GaN - nu_AlN)

def F1(hc, xg):
    try:
        bx = b(xg)
        fx = f(xg)
        nux = nu(xg)
        if hc <= bx or fx == 0:
            return np.nan
        return (bx / (2 * np.pi * fx)) * (1 / (1 + nux)) * (np.log(hc / bx) + 1) - hc
    except Exception:
        return np.nan

# 結果格納用リスト
q1_list = []
q2_list = []

# 探索ループ
for n in range(1, 101):
    xg = 0.01 * n
    bx = b(xg)
    hc_min = bx * 1.01
    hc_max = 1e-6  # 十分広い範囲で探索
    F_min = F1(hc_min, xg)
    F_max = F1(hc_max, xg)

    try:
        if np.isnan(F_min) or np.isnan(F_max):
            raise ValueError("F1 = nan")
        if F_min * F_max > 0:
            raise ValueError("符号が変わらない")

        sol = root_scalar(F1, args=(xg,), bracket=[hc_min, hc_max], method='brentq')
        if sol.converged:
            hc = sol.root
            q1_list.append(1 - xg)
            q2_list.append(hc * 1e9)
            print(f"xg={xg:.2f}, hc={hc * 1e9:.2f} nm")
        else:
            print(f"xg={xg:.2f} → 未収束")
    except Exception as e:
        print(f"xg={xg:.2f} → 解なし: {e}")

        # オプション：F1の挙動を表示（必要な場合だけ）
        hc_vals = np.logspace(np.log10(hc_min), np.log10(hc_max), 200)
        F_vals = [F1(hc, xg) for hc in hc_vals]

        plt.figure(figsize=(5, 3))
        plt.plot(hc_vals, F_vals, label=f'xg={xg:.2f}')
        plt.axhline(0, color='gray', linestyle='--')
        plt.xscale('log')
        plt.xlabel("hc [m]")
        plt.ylabel("F1(hc)")
        plt.title(f"F1 vs hc (xg={xg:.2f})")
        plt.grid(True, which='both', ls='--')
        plt.tight_layout()
        plt.show()

# データ配列
A = np.column_stack((q1_list, q2_list))

# プロット
fig, ax = plt.subplots(figsize=(6, 4))
ax.plot(q1_list, q2_list, marker='o', linestyle='-')

# 軸範囲とスケール
ax.set_xlim(0, 1)
ax.set_ylim(1, 1000)
ax.set_yscale('log')

# ラベル・タイトル
ax.set_xlabel('Al content')
ax.set_ylabel('Critical thickness (nm)')
ax.set_title('Critical thickness')

# 目盛りを上下左右に
ax.tick_params(
    axis='both', which='both',
    direction='in',       # 目盛を内向きに
    top=True, bottom=True,
    left=True, right=True
)

# 副次目盛りの表示（logスケールに対応）
from matplotlib.ticker import AutoMinorLocator, LogLocator

ax.xaxis.set_minor_locator(AutoMinorLocator())
ax.yaxis.set_minor_locator(LogLocator(base=10.0, subs=np.arange(2, 10)*0.1, numticks=12))
ax.tick_params(which='minor', length=4)

# グリッドなし
ax.grid(False)

# レイアウト調整
plt.tight_layout()
plt.show()

# データ保存
np.savetxt("Thickness.dat", A, fmt="%.6f", header="1 - xg\tThickness [nm]")

